export default class Data {
  categories = [
  { id: 1, name: "General" },
  { id: 2, name: "Programming" },
  { id: 3, name: "UI/UX" },
  { id: 4, name: "Business" },
];
    courses = [
  {
    id: 1,
    title: "C++ Programming Fundamentals",
    discription: "Learn the fundamentals of C++ from scratch and build strong programming skills.",
    mentor: "Hazem Abu Zaid",
    price: 49,
    categories: ["Programming", "C++"],
    image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800",
  },
  {
    id: 2,
    title: "React.js Complete Guide",
    discription: "Master React and build modern web applications with hooks and routing.",
    mentor: "Ahmed Almasri",
    price: 69,
    categories: ["Web", "React"],
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800",
  },
  {
    id: 3,
    title: "UI/UX Design Essentials",
    discription: "Learn design principles, wireframing, prototyping, and user experience.",
    mentor: "Sarah Khaled",
    price: 39,
    categories: ["UI/UX"],
    image: "https://images.unsplash.com/photo-1559028012-481c04fa702d?w=800",
  },
  {
    id: 4,
    title: "Machine Learning Basics",
    discription: "An introduction to machine learning algorithms and practical applications.",
    mentor: "Mohammad Ali",
    price: 89,
    categories: ["AI", "Data Science"],
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800",
  },
  {
    id: 5,
    title: "Node.js Backend Development",
    discription: "Build scalable REST APIs using Node.js, Express, and MongoDB.",
    mentor: "Omar Hassan",
    price: 59,
    categories: ["Backend", "Node.js"],
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800",
  },
  {
    id: 6,
    title: "Flutter Mobile Apps",
    discription: "Create beautiful cross-platform mobile applications with Flutter.",
    mentor: "Lina Ahmad",
    price: 74,
    categories: ["Mobile", "Flutter"],
    image: "https://images.unsplash.com/photo-1526498460520-4c246339dccb?w=800",
  },
  {
    id: 7,
    title: "Cyber Security Fundamentals",
    discription: "Understand networking, vulnerabilities, and cybersecurity practices.",
    mentor: "Yousef Hamdan",
    price: 55,
    categories: ["Cyber Security"],
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800",
  },
  {
    id: 8,
    title: "Python for Data Analysis",
    discription: "Analyze data efficiently using Python, Pandas, and NumPy.",
    mentor: "Rama Saad",
    price: 65,
    categories: ["Python", "Data Science"],
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800",
  },
];
 lessons = [
  {
    id: 1,
    order: 1,
    title: "Introduction to React",
    duration: "05:20",
    type: "Video",
  },
  {
    id: 2,
    order: 2,
    title: "Understanding Components",
    duration: "12:15",
    type: "Video",
  },
  {
    id: 3,
    order: 3,
    title: "JSX Fundamentals",
    duration: "08:40",
    type: "Video",
  },
  {
    id: 4,
    order: 4,
    title: "Props and Data Flow",
    duration: "14:10",
    type: "Video",
  },
  {
    id: 5,
    order: 5,
    title: "State Management",
    duration: "16:35",
    type: "Video",
  },
  {
    id: 6,
    order: 6,
    title: "React Hooks",
    duration: "18:00",
    type: "Video",
  },
];
}